[package]
name = "taskman-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
taskman-domain = { path = "../taskman-domain" }

[target.'cfg(target_os = "linux")'.dependencies]
taskman-platform-linux = { path = "../taskman-platform-linux" }

[target.'cfg(target_os = "windows")'.dependencies]
taskman-platform-windows = { path = "../taskman-platform-windows" }
